name: Build Test

on:
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        # https://github.com/hajimehoshi/oto#linux
      - name: Install ALSA
        run: sudo apt install libasound2-dev
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      - name: Dry Run
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: goreleaser build --snapshot
